version: '2'
services:
  cognos-categories-api:
    container_name: cognos-categories-api
    build:
      context: cognos-categories-api
      dockerfile: Dockerfile
    image: cognos-categories-api:latest
    ports:
      - 18888:8888
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
