version: '3'
services:
  cognos-categories-api:
    container_name: cognos-categories-api
    build:
      context: docker-cognos-categories-api
      dockerfile: Dockerfile
    image: cognos-categories-api:latest
    ports:
      - 18888:8888
    networks:
      - spring-cloud-network
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  spring-cloud-network:
    driver: bridge
